# Generated by Django 3.2.9 on 2021-11-05 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('Ropa_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(null=True, upload_to='images/H1F.png')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descrpcion', models.CharField(max_length=50)),
                ('TallaS', models.IntegerField(default=6)),
                ('TallaM', models.IntegerField(default=9)),
                ('Costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('Estado', models.BooleanField(verbose_name=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('CategoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Estado', models.BooleanField(verbose_name=True)),
                ('CursoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ropa')),
            ],
        ),
    ]
