# Generated by Django 3.2.9 on 2021-11-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='CursoID',
        ),
        migrations.AddField(
            model_name='ropa',
            name='CategoriaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.categorias'),
        ),
    ]
